# Generated by Django 5.2.8 on 2025-12-01 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('priority', models.IntegerField(default=1)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
