# Generated by Django 5.2.8 on 2025-12-01 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingitem',
            name='purchased',
            field=models.BooleanField(default=False),
        ),
    ]
