# Generated by Django 5.2.8 on 2025-12-05 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0002_shoppingitem_purchased'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingitem',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=1),
        ),
    ]
